class PrefKey{
  static const String PREF_KEY_USER_LOGIN_ROLE= "PREF_KEY_USER_LOGIN_ROLE";
  static const String PREF_KEY_USERID= "PREF_KEY_USERID";
  static const String PREF_KEY_PROFILE_SLIDE_SETUP= "PREF_KEY_PROFILE_SLIDE_SETUP";
  static const String PREF_KEY_NAME= "PREF_KEY_NAME";
  static const String PREF_KEY_MOBILE= "PREF_KEY_MOBILE";
  static const String PREF_KEY_USER_LOGIN_TOKEN= "PREF_KEY_USER_LOGIN_TOKEN";
  static const String PREF_KEY_DEVICE_REGISTERED= "PREF_KEY_PROFILE_SLIDE_SETUP";
  static const String PREF_KEY_EMAIL= "PREF_KEY_EMAIL";
}